version: '3.9'

services:
    app:
        container_name: cypherx
        build: .
        tty: true
        volumes:
            - .:/go/src/app
    neo4j:
        image: neo4j
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            NEO4J_AUTH: none